### ISSUE TITLE
No access to coins_auth repo

### ISSUE THREAD

**Issue by chrisgorgo** [MRN-Code/nodeapi#53]
I'm trying to run nodeapi (to be able to run coinstac), but it seems it is dependent on a private repo:

```
orange:nodeapi filo$ npm run startdev

> nodeapi@1.3.0 startdev /Users/filo/drive/workspace/nodeapi
> babel-node src/index.js --development -c

Running with COINS_ENV: development
Including New Relic agent
New Relic agent reporting disabled
module.js:328
    throw err;
    ^

Error: Cannot find module '/coins/config/dbmap.json'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/filo/drive/workspace/nodeapi/src/lib/utils/get-db-config.js:5:21)
    at Module._compile (module.js:398:26)
    at normalLoader (/Users/filo/drive/workspace/nodeapi/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/filo/drive/workspace/nodeapi/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/filo/drive/workspace/nodeapi/src/lib/utils/get-knex-config.js:3:16)
    at Module._compile (module.js:398:26)
    at normalLoader (/Users/filo/drive/workspace/nodeapi/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/filo/drive/workspace/nodeapi/node_modules/babel-core/lib/api/register/node.js:216:7)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "run" "startdev"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! nodeapi@1.3.0 startdev: `babel-node src/index.js --development -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodeapi@1.3.0 startdev script 'babel-node src/index.js --development -c'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodeapi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node src/index.js --development -c
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeapi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/filo/drive/workspace/nodeapi/npm-debug.log
```

According to the [documentation](https://github.com/MRN-Code/nodeapi/blob/develop/REQUIREMENTS.md) /coins/config/ should be obtained from the [coins_auth repo](https://github.com/MRN-Code/nodeapi/blob/develop/MRN-Code/coins_auth) which is currently private. Is there a way for non-MRN users to run nodeapi and coninstac?

**Comment by dylancwood** [comment]
Thanks for bringing this up. As mentioned previously, you are the first non-MRN person to run the API or COINSTAC. We are excited that you are trying to run the applications yourself, and we will do everything we can to support you.

I will work on documentation that includes directions on formatting your own `dbmap.json`. 

We should probably also make the path to the dbmap configurable so that users do not need to create a `/coins` directory.

**Comment by cdaringe** [comment]
this is really a symptom of #50 not being completed.  #50 is a key objective for the team.  closing with focus on #50
