### ISSUE TITLE
API crashes on ENTER via stdin

### ISSUE THREAD

**Issue by cdaringe** [MRN-Code/nodeapi#56]
loading the api then hitting the ENTER key produces the following.

```
cdieringer@Snapper-osx:~/node/nodeapi$ node dist/ -c
Running with COINS_ENV: development
Including New Relic agent
New Relic agent reporting disabled
Using default dbmap.json
Including COINSTAC routes
160115/112819.594, [log,startup], data: server running at: http://Snapper-osx:8800

/Users/cdieringer/node/nodeapi/dist/index.js:94
    server.plugins.logger.logError(['stderr'], data);
                         ^

TypeError: Cannot read property 'logError' of undefined
    at WriteStream.<anonymous> (/Users/cdieringer/node/nodeapi/dist/index.js:94:26)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at WriteStream.Readable.push (_
```

**Comment by cdaringe** [comment]
fixed it :)
